public import Institute_Model
public import Institute_Inventory

public import File_System
public import Package_Manager
public import Xcode_Scheme

extension Institute.Xcode {
    /// The one generated shared scheme, which is what makes the whole
    /// selection buildable in a single `xcodebuild` invocation.
    ///
    /// Xcode autogenerates a scheme per package product, so a selection of N
    /// packages arrives with hundreds of schemes and no scheme that covers
    /// more than one package — measured: a three-package workspace enumerates
    /// nine, a 199-package one enumerates 1184, and `xcodebuild` accepts
    /// exactly one `-scheme`. Building the selection through those would be N
    /// invocations again, which is the thing being replaced.
    ///
    /// A *shared* scheme may name buildables in more than one container, and
    /// that is the whole mechanism: one scheme, one `BuildActionEntry` per
    /// compilable target across every selected package, `parallelizeBuildables`
    /// on. Xcode merges them into a single dependency graph, schedules it
    /// across all cores, and compiles each shared dependency once rather than
    /// once per package.
    public enum Scheme {}
}

extension Institute.Xcode.Scheme {
    /// The generated scheme's name. Xcode suppresses its autogenerated scheme
    /// for any target a shared scheme already covers, so this name is also
    /// what the covered targets stop being listed under.
    public static let name = "Institute"

    /// One compilable target, and the workspace-relative reference of the
    /// package that declares it.
    public struct Buildable: Sendable, Equatable {
        /// The same relative spelling the workspace document uses —
        /// `../<inventory-derived-reference>`. Never absolute.
        public let reference: Swift.String
        public let target: Swift.String

        public init(reference: Swift.String, target: Swift.String) {
            self.reference = reference
            self.target = target
        }
    }
}

extension Institute.Xcode.Scheme {
    public static func document(
        _ buildables: [Buildable]
    ) -> Xcode_Scheme.Xcode.Scheme {
        // Module-qualified: inside `extension Institute.Xcode.Scheme` the
        // unqualified name `Xcode` rebinds to `Institute.Xcode`, so a bare
        // `Xcode.Scheme` would resolve to this very type. Same shadow, and
        // same resolution, as `Institute.Xcode.document(_:)` above.
        Xcode_Scheme.Xcode.Scheme(
            build: buildables.map { buildable in
                .init(
                    reference: .init(
                        blueprint: buildable.target,
                        name: buildable.target,
                        container: "container:\(buildable.reference)"
                    )
                )
            },
            test: []
        )
    }

    public static func render(_ buildables: [Buildable]) -> Swift.String {
        document(buildables).xml
    }

    public static func path(at root: File.Directory) -> File {
        root[directory: "institute.xcworkspace"][directory: "xcshareddata"][directory: "xcschemes"][
            file: "\(name).xcscheme"
        ]
    }

    public static func contents(at root: File.Directory) -> Swift.String? {
        do throws(Either<File.System.Read.Full.Error, Never>) {
            return try path(at: root).read.full { bytes in
                var storage = [Byte]()
                storage.reserveCapacity(bytes.count)
                for index in bytes.indices {
                    storage.append(bytes[index])
                }
                return Swift.String(decoding: storage, as: Swift.UTF8.self)
            }
        } catch {
            return nil
        }
    }

    /// Whether the scheme on disk is byte-identical to the one the current
    /// manifests render.
    ///
    /// This is the coverage gate, and it has to be a *structural* one. A
    /// `BuildableReference` whose blueprint names no target in its container
    /// is silently dropped: measured on this machine, a scheme carrying one
    /// fabricated entry alongside valid ones exits 0 and prints
    /// `** BUILD SUCCEEDED **` without ever building that package. Only a
    /// scheme in which *every* entry is unmatched fails, with exit 66. So a
    /// name that drifts from its manifest does not fail the build — it
    /// shrinks it, and the shrunken build still looks green.
    ///
    /// Nothing in the build's own output can close that gap either: an
    /// up-to-date target compiles nothing, so "this module is absent from the
    /// log" and "this package was never in the scheme" are the same
    /// observation. The only honest gate is to re-render from the manifests
    /// and compare before building, which is what this is for.
    public static func current(_ buildables: [Buildable], at root: File.Directory) -> Swift.Bool {
        contents(at: root) == render(buildables)
    }

    public static func write(
        _ buildables: [Buildable],
        at root: File.Directory
    ) throws(Institute.Error) {
        let bundle = root[directory: "institute.xcworkspace"]
        do throws(Xcode_Scheme.Xcode.Scheme.Error) {
            try document(buildables).write(name, to: bundle.description)
        } catch {
            throw .filesystem("cannot write \(path(at: root)): \(error)")
        }
    }
}

extension Institute.Xcode.Scheme {
    /// Every compilable target of every selected repository, in inventory
    /// order, read from the manifests.
    ///
    /// Read, not guessed, because of the silent-drop behaviour documented on
    /// ``current(_:at:)``. The cost is one `swift package dump-package` per
    /// selected repository, which is the cost `Institute.Doctor` already pays
    /// for its manifest-identity check; this is not a new class of work.
    ///
    /// Test targets are excluded because they are never in scope for a build
    /// here. Plugin, macro, binary, and system targets are excluded because
    /// they are not blueprints a consumer builds directly — whatever needs
    /// them pulls them in as dependencies of a target that is listed.
    ///
    /// A repository with no `Package.swift` contributes nothing and is
    /// skipped: the inventory holds specification and document repositories
    /// too, and those have no targets to build. A repository that *does* carry
    /// a manifest which then fails to evaluate is an error, not an omission —
    /// skipping it would produce a scheme that builds less than the selection
    /// while still reporting success, which is exactly the failure this whole
    /// path is arranged to prevent. The distinction is the point: "not a
    /// package" and "a package I could not read" must not reach the same
    /// outcome.
    public static func buildables(
        for repositories: [Institute.Repository],
        at root: Institute.Root,
        packages: Package.Manager = .init()
    ) throws(Institute.Error) -> [Buildable] {
        var buildables = [Buildable]()
        for repository in repositories {
            let directory = try Institute.Layout.directory(for: repository, at: root.hierarchy)
            guard directory[file: "Package.swift"].stat.exists else { continue }
            let evaluation: Package.Manifest.Evaluation
            do throws(Package.Manager.Error) {
                evaluation = try packages.evaluation(at: directory.description)
            } catch {
                throw .configuration(
                    "cannot evaluate the manifest of \(repository.name) at \(directory): \(error)"
                )
            }
            let reference = "../\(Institute.Layout.reference(for: repository))"
            for target in evaluation.targets {
                // Switched inline rather than through a helper taking a
                // `Target.Kind`: naming that type here would resolve through
                // the enclosing `Institute` scopes first, and an exhaustive
                // switch makes a newly added kind a compile error rather than
                // a target that silently stops being built.
                switch target.kind {
                case .regular, .executable:
                    buildables.append(.init(reference: reference, target: target.name.underlying))
                case .test, .plugin, .binary, .system, .macro:
                    continue
                }
            }
        }
        return buildables
    }
}
