public import Institute_Model
public import Institute_Inventory

public import Build_Coordinator
public import File_System

extension Institute.Composed {
    /// The generated composed root: one synthetic target,
    /// ``targetName``, depending on every library product of every
    /// contributing repository. Building it (`swift build`, no
    /// arguments) compiles the whole reachable composed closure once —
    /// the SwiftPM analogue of ``Xcode/Scheme``'s shared scheme.
    ///
    /// Unlike `institute.xcworkspace`/``Xcode/Scheme``, this directory is
    /// never detected-as-stale-and-refused: nothing else writes it
    /// between one coherence run's own write and that same run's build,
    /// so there is no window in which a persisted copy could go stale.
    /// ``write(_:swift:at:)`` regenerates it fresh at the start of every
    /// run instead.
    public enum Root {}
}

extension Institute.Composed.Root {
    /// The composed root's directory name, at the workspace checkout
    /// root — ignored, generated, never committed, exactly like
    /// `institute.xcworkspace`.
    public static let directoryName: File.Path.Component = "institute-composed-root"

    /// The composed root's one synthetic target and package name.
    public static let targetName: File.Path.Component = "CoherenceComposedRoot"

    public static func directory(at checkout: File.Directory) -> File.Directory {
        checkout[directory: directoryName]
    }

    static func manifestFile(at checkout: File.Directory) -> File {
        directory(at: checkout)[file: "Package.swift"]
    }

    static func sourceFile(at checkout: File.Directory) -> File {
        directory(at: checkout)[directory: "Sources"][directory: targetName][file: "Root.swift"]
    }

    /// The repositories the composed root actually declares a
    /// dependency on — those exposing at least one library product —
    /// sorted by reference so the render is deterministic run over run
    /// on the same selection.
    static func contributing(_ manifests: [Institute.Composed.Manifest]) -> [Institute.Composed.Manifest] {
        manifests.filter { !$0.libraryProducts.isEmpty }.sorted { $0.reference < $1.reference }
    }

    /// The whole composed reachable population: the buildable-target
    /// count of every contributing repository. See ``Composed``'s
    /// documentation for why a repository with no library product is
    /// excluded here rather than silently folded in.
    public static func expectedTargetCount(in manifests: [Institute.Composed.Manifest]) -> Swift.Int {
        contributing(manifests).reduce(0) { $0 + $1.buildableTargetCount }
    }

    /// The synthetic manifest's text.
    public static func render(_ manifests: [Institute.Composed.Manifest], swift: Swift.String) -> Swift.String {
        let selected = contributing(manifests)
        var lines = [Swift.String]()
        lines.append("// swift-tools-version: \(swift)")
        lines.append("")
        lines.append("import PackageDescription")
        lines.append("")
        lines.append("let package = Package(")
        lines.append("    name: \"\(targetName)\",")
        lines.append("    dependencies: [")
        for manifest in selected {
            lines.append("        .package(path: \"\(manifest.reference)\"),")
        }
        lines.append("    ],")
        lines.append("    targets: [")
        lines.append("        .target(")
        lines.append("            name: \"\(targetName)\",")
        lines.append("            dependencies: [")
        for manifest in selected {
            for product in manifest.libraryProducts {
                lines.append(
                    "                .product(name: \"\(product)\", package: \"\(manifest.package)\"),"
                )
            }
        }
        lines.append("            ]")
        lines.append("        )")
        lines.append("    ]")
        lines.append(")")
        lines.append("")
        return lines.joined(separator: "\n")
    }

    /// The synthetic target's one source file. Its contents never depend
    /// on the selection — the composed graph is compiled through the
    /// manifest's declared product dependencies, not through anything
    /// this file imports or references — so it is written once per run
    /// unconditionally, exactly like the manifest.
    static let source = """
        // Generated by `institute coherence` for the swiftpm-composed-root
        // build path (swift-institute/institute-application#81). This file exists only
        // so \(targetName) is a valid SwiftPM target; the composed graph is
        // compiled through its declared product dependencies, not this
        // file's contents.

        """

    /// Writes the composed root fresh, replacing any prior generation.
    public static func write(
        _ manifests: [Institute.Composed.Manifest],
        swift: Swift.String,
        at checkout: File.Directory
    ) throws(Institute.Error) {
        let root = directory(at: checkout)
        do throws(File.System.Create.Directory.Error) {
            try root[directory: "Sources"][directory: targetName].create.recursive()
        } catch {
            throw .filesystem("cannot create \(root): \(error)")
        }
        do throws(File.System.Write.Atomic.Error) {
            try manifestFile(at: checkout).write.atomic(render(manifests, swift: swift))
        } catch {
            throw .filesystem("cannot write \(manifestFile(at: checkout)): \(error)")
        }
        do throws(File.System.Write.Atomic.Error) {
            try sourceFile(at: checkout).write.atomic(source)
        } catch {
            throw .filesystem("cannot write \(sourceFile(at: checkout)): \(error)")
        }
    }
}

extension Institute.Composed.Root {
    /// Builds the composed root with `swift build`, optionally capturing
    /// diagnostics for the coherence instrument's mechanical attribution
    /// — the SwiftPM analogue of
    /// ``Xcode/Build/run(fresh:arguments:capturingDiagnostics:)``.
    public static func build(
        at checkout: File.Directory,
        fresh: Swift.Bool,
        arguments: [Swift.String],
        capturingDiagnostics: Swift.Bool,
        coordinator: Build_Coordinator.Build.Coordinator = .init()
    ) throws(Institute.Error) -> Build_Coordinator.Build.Coordinator.Result {
        do throws(Build_Coordinator.Build.Error) {
            return try coordinator.run(
                .build,
                at: directory(at: checkout).description,
                fresh: fresh,
                arguments: arguments,
                capturingDiagnostics: capturingDiagnostics
            )
        } catch {
            throw .process("\(error)")
        }
    }
}
