import File_System
import Foundation
import Testing

@testable import Workspace_Application

extension Workspace.Context {
    @Suite
    struct Test {
        @Suite struct Unit {}
        @Suite struct `Edge Case` {}
        @Suite struct Integration {}
    }
}

extension Workspace.Context.Test {
    private static let marker =
        "<!-- Generated by `institute context install`; edit the canonical template in Workspace/Context. -->"

    /// Materializes a hierarchy and an account root that are siblings, never
    /// nested, so nothing here can pass by resolving relative to the checkout.
    ///
    /// - Parameter roots: The canonical skill roots to materialize. The default
    ///   is all four; passing fewer models an account that clones fewer
    ///   repositories, which is every contributor outside the Institute.
    private static func fixture<Result>(
        roots: Set<Swift.String> = [
            "public-skill", "internal-skill", "engagement-skill", "rule-skill",
        ],
        _ body: (Workspace.Context) throws -> Result
    ) throws -> Result {
        let base = FileManager.default.temporaryDirectory.appending(path: UUID().uuidString)
        defer { try? FileManager.default.removeItem(at: base) }
        try FileManager.default.createDirectory(at: base, withIntermediateDirectories: true)

        let temporary = try File.Directory(validating: base.path)
        let home = temporary[directory: "home"]
        let entry = temporary[directory: "entry"]
        let institute = entry[directory: "swift-institute"]
        let checkout = institute[directory: "Workspace"]
        let templates = checkout[directory: "Context"]
        let publicSkills = institute[directory: "Skills"]
        let internalSkills = institute[directory: "Internal"][directory: "Skills"]
        let engagementSkills = institute[directory: "Engagement"][directory: "Skills"]
        let ruleSkills = entry[directory: "rule-institute"][directory: "Skills"]

        let sources = [
            (publicSkills, "public-skill"),
            (internalSkills, "internal-skill"),
            (engagementSkills, "engagement-skill"),
            (ruleSkills, "rule-skill"),
        ].filter { roots.contains($0.1) }

        try home.create.recursive()
        try templates.create.recursive()
        try templates[file: "AGENTS.md"].write.atomic(
            "\(Self.marker)\n# Fixture\n"
        )
        for (root, name) in sources {
            let skill = root[directory: try File.Path.Component(name)]
            try skill.create.recursive()
            try skill[file: "SKILL.md"].write.atomic(
                "---\nname: \(name)\ndescription: fixture\n---\n\n# Fixture\n"
            )
        }

        return try body(
            Workspace.Context(
                root: Workspace.Root(checkout: checkout),
                home: File.Directory(try File.System.Canonical.resolve(home.path))
            )
        )
    }

    /// The installed projection directory for a fixture context.
    fileprivate static func projections(_ context: Workspace.Context) -> File.Directory {
        context.home[directory: ".claude"][directory: "skills"]
    }
}

extension Workspace.Context.Test.Unit {
    @Test
    func `install materializes documents and every canonical skill source`() throws {
        try Workspace.Context.Test.fixture { context in
            try context.install()

            let skills = Workspace.Context.Test.projections(context)
            let institute = context.entry[directory: "swift-institute"]

            #expect(try context.diagnostics().isEmpty)
            #expect(
                try File.System.Link.Read.Target.target(
                    of: context.home[directory: ".agents"].path / "skills"
                ) == skills.path
            )
            #expect(
                try File.System.Link.Read.Target.target(
                    of: context.entry[file: "CLAUDE.md"].path
                ) == File.Path("AGENTS.md")
            )
            #expect(
                try File.System.Link.Read.Target.target(of: skills.path / "public-skill")
                    == institute[directory: "Skills"].path / "public-skill"
            )
            #expect(
                try File.System.Link.Read.Target.target(of: skills.path / "internal-skill")
                    == institute[directory: "Internal"][directory: "Skills"].path
                        / "internal-skill"
            )
            #expect(
                try File.System.Link.Read.Target.target(of: skills.path / "engagement-skill")
                    == institute[directory: "Engagement"][directory: "Skills"].path
                        / "engagement-skill"
            )
            #expect(
                try File.System.Link.Read.Target.target(of: skills.path / "rule-skill")
                    == context.entry[directory: "rule-institute"][directory: "Skills"].path
                        / "rule-skill"
            )
            // The projection is not reachable by walking down from the checkout,
            // which is the whole point: it is reachable from every root instead.
            #expect(!context.entry[directory: ".claude"].stat.exists)
            #expect(!context.entry[directory: ".agents"].stat.exists)
            #expect(
                try File.System.Metadata.Permissions(
                    at: context.entry[file: "AGENTS.md"].path
                ) == .defaultFile
            )
        }
    }

    @Test
    func `install is idempotent`() throws {
        try Workspace.Context.Test.fixture { context in
            try context.install()
            try context.install()

            #expect(try context.diagnostics().isEmpty)
        }
    }

    @Test
    func `install refreshes its generated document`() throws {
        try Workspace.Context.Test.fixture { context in
            try context.install()
            try context.root.checkout[directory: "Context"][file: "AGENTS.md"]
                .write.atomic("\(Workspace.Context.Test.marker)\n# Revised fixture\n")

            try context.install()

            #expect(try context.diagnostics().isEmpty)
        }
    }

    @Test
    func `install removes a retired generated skill projection`() throws {
        try Workspace.Context.Test.fixture { context in
            try context.install()
            let institute = context.entry[directory: "swift-institute"]
            let skill = institute[directory: "Skills"][directory: "public-skill"]
            try skill[file: "SKILL.md"].delete()

            try context.install()

            let skills = Workspace.Context.Test.projections(context)
            #expect(!skills[file: "public-skill"].stat.exists)
            #expect(try context.diagnostics().isEmpty)
        }
    }
}

extension Workspace.Context.Test.`Edge Case` {
    @Test
    func `install rejects malformed canonical skill metadata before projecting`() throws {
        try Workspace.Context.Test.fixture { context in
            let institute = context.entry[directory: "swift-institute"]
            let publicSkills = institute[directory: "Skills"]
            let publicSkill = publicSkills[directory: "public-skill"]
            let skill = publicSkill[file: "SKILL.md"]
            try skill.write.atomic(
                """
                ---
                name: public-skill
                description: fixture
                layer: implementation
                ---
                # Fixture
                """
            )

            #expect(throws: Workspace.Error.self) {
                try context.install()
            }
            #expect(!context.home[directory: ".claude"].stat.exists)
        }
    }

    @Test
    func `install refuses an unmanaged root document before creating projections`() throws {
        try Workspace.Context.Test.fixture { context in
            try context.entry[file: "AGENTS.md"].write.atomic("# Local instructions\n")

            #expect(throws: Workspace.Error.self) {
                try context.install()
            }
            #expect(
                !context.home[directory: ".claude"].stat.exists
            )
        }
    }

    @Test
    func `install migrates the generated Claude document and checkout-local Codex link`() throws {
        try Workspace.Context.Test.fixture { context in
            try context.entry[file: "CLAUDE.md"].write.atomic(
                "\(Workspace.Context.Test.marker)\n@AGENTS.md\n"
            )
            let legacy = context.entry[directory: ".agents"]
            try legacy.create.recursive()
            try FileManager.default.createSymbolicLink(
                atPath: (legacy.path / "skills").description,
                withDestinationPath: Workspace.Context.Test.projections(context).path.description
            )

            try context.install()

            #expect(try context.diagnostics().isEmpty)
            #expect(
                try File.System.Link.Read.Target.target(
                    of: context.entry[file: "CLAUDE.md"].path
                ) == File.Path("AGENTS.md")
            )
            #expect(!legacy[file: "skills"].stat.exists)
            #expect(
                try File.System.Link.Read.Target.target(
                    of: context.home[directory: ".agents"].path / "skills"
                ) == Workspace.Context.Test.projections(context).path
            )
        }
    }

    @Test
    func `install refuses an unmanaged Claude document before creating projections`() throws {
        try Workspace.Context.Test.fixture { context in
            try context.entry[file: "CLAUDE.md"].write.atomic("# Local Claude instructions\n")

            #expect(throws: Workspace.Error.self) {
                try context.install()
            }
            #expect(!context.home[directory: ".claude"].stat.exists)
            #expect(!context.home[directory: ".agents"].stat.exists)
        }
    }

    @Test
    func `install refuses a divergent checkout-local Codex link`() throws {
        try Workspace.Context.Test.fixture { context in
            let legacy = context.entry[directory: ".agents"]
            try legacy.create.recursive()
            try FileManager.default.createSymbolicLink(
                atPath: (legacy.path / "skills").description,
                withDestinationPath: context.home[directory: "elsewhere"].path.description
            )

            #expect(
                try context.diagnostics().contains {
                    $0.contains("retired context link has the wrong target")
                }
            )
            #expect(throws: Workspace.Error.self) {
                try context.install()
            }
            #expect(!context.home[directory: ".claude"].stat.exists)
            #expect(!context.home[directory: ".agents"].stat.exists)
        }
    }

    @Test
    func `install preserves a user alias into a canonical skill root`() throws {
        try Workspace.Context.Test.fixture { context in
            try context.install()
            let institute = context.entry[directory: "swift-institute"]
            let canonical = institute[directory: "Skills"].path / "public-skill"
            let alias = Workspace.Context.Test.projections(context).path / "user-alias"
            try FileManager.default.createSymbolicLink(
                atPath: alias.description,
                withDestinationPath: canonical.description
            )

            try context.install()

            #expect(try File.System.Link.Read.Target.target(of: alias) == canonical)
            #expect(try context.diagnostics().isEmpty)
        }
    }

    @Test
    func `install projects the canonical roots this account carries and skips the rest`() throws {
        try Workspace.Context.Test.fixture(roots: ["public-skill"]) { context in
            try context.install()

            let skills = Workspace.Context.Test.projections(context)
            #expect(skills[file: "public-skill"].stat.exists)
            #expect(!skills[file: "internal-skill"].stat.exists)
            #expect(!skills[file: "engagement-skill"].stat.exists)
            #expect(!skills[file: "rule-skill"].stat.exists)
            #expect(try context.diagnostics().isEmpty)
        }
    }

    @Test
    func `install leaves a projection into a root it does not own alone`() throws {
        try Workspace.Context.Test.fixture(roots: ["public-skill"]) { context in
            try context.install()

            // A skill installed from somewhere outside every canonical Institute
            // root — a personal dotfiles checkout, say. Workspace does not know
            // it exists and must never remove it.
            let foreign = context.home[directory: "elsewhere"][directory: "foreign-skill"]
            try foreign.create.recursive()
            let alias = Workspace.Context.Test.projections(context).path / "foreign-skill"
            try FileManager.default.createSymbolicLink(
                atPath: alias.description,
                withDestinationPath: foreign.path.description
            )

            try context.install()

            #expect(try File.System.Link.Read.Target.target(of: alias) == foreign.path)
            #expect(try context.diagnostics().isEmpty)
        }
    }
}

// MARK: - An install that projects nothing is not a success (#58)

extension Workspace.Context.Test.`Edge Case` {
    /// The defect this guards: a hierarchy carrying no canonical skill root
    /// printed `installed and verified`, exited 0, and wrote no projection —
    /// a report indistinguishable from a complete install.
    @Test
    func `install with no canonical skill root fails and names every root it looked for`() throws {
        try Workspace.Context.Test.fixture(roots: []) { context in
            #expect(throws: Workspace.Error.self) {
                try context.install()
            }

            do {
                try context.install()
                Issue.record("install reported success with no canonical skill root")
            } catch let error as Workspace.Error {
                let message = "\(error)"
                #expect(message.contains("no canonical skill root resolved"))
                // Naming the roots is the difference between a failure a
                // contributor can act on and one they can only report.
                #expect(message.contains("swift-institute/Skills"))
                #expect(message.contains("rule-institute/Skills"))
            }
        }
    }

    @Test
    func `check reports a hierarchy that projects nothing rather than calling it current`() throws {
        try Workspace.Context.Test.fixture(roots: []) { context in
            let diagnostics = try context.diagnostics()

            #expect(diagnostics.contains { $0.contains("no canonical skill root resolved") })
        }
    }

    /// The positive control for both assertions above. Without it, a passing
    /// negative control proves only that these fixtures fail — which they
    /// would also do if the fixture itself were broken.
    @Test
    func `install reports the count and the roots it projected from`() throws {
        try Workspace.Context.Test.fixture(roots: ["public-skill", "rule-skill"]) { context in
            let projection = try context.install()

            #expect(projection.skills == ["public-skill", "rule-skill"])
            #expect(projection.sources.count == 2)
            #expect(projection.summary.contains("2 skill(s) from 2 root(s)"))
        }
    }
}
