@testable import Institute_Model
@testable import Institute_Inventory
@testable import Institute_Dependency
@testable import Institute_Development
@testable import Institute_Lint
@testable import Institute_Pages
@testable import Institute_Doctor
@testable import Institute_Conversion
@testable import Institute_Instruments
@testable import Institute_GitHub

import Testing

@testable import Build_Coordinator

@Suite
struct `Build Institute Tests` {
    private static let workspace = Build.Workspace(
        bundle: "/checkout/institute.xcworkspace",
        scheme: "Institute"
    )

    @Test
    func `invocation drives xcodebuild through the workspace and the shared scheme`() throws {
        let invocation = try Self.workspace.invocation(jobs: 3, arguments: [])

        #expect(
            invocation == [
                "xcodebuild",
                "-workspace", "/checkout/institute.xcworkspace",
                "-scheme", "Institute",
                "-destination", "platform=macOS",
                "-skipMacroValidation", "-skipPackagePluginValidation",
                "ONLY_ACTIVE_ARCH=YES",
                "build",
            ]
        )
    }

    @Test
    func `jobs is accepted and deliberately not forwarded`() throws {
        // `jobs` is SwiftPM's `-j`. xcodebuild schedules the merged graph
        // itself — measured, it chose `-j8` here unprompted — so forwarding a
        // SwiftPM job count would substitute a second opinion for the one the
        // tool already formed, and a small explicit `jobs:` would throttle the
        // only thing this operation is for.
        let three = try Self.workspace.invocation(jobs: 3, arguments: [])
        let sixteen = try Self.workspace.invocation(jobs: 16, arguments: [])

        #expect(three == sixteen)
        #expect(!three.contains("-jobs"))
        #expect(!three.contains("-j"))
    }

    @Test
    func `a caller may still ask for a job cap explicitly`() throws {
        let invocation = try Self.workspace.invocation(jobs: 3, arguments: ["-jobs", "2"])

        #expect(invocation.suffix(2) == ["-jobs", "2"])
    }

    @Test
    func `isolated derived data is placed by the caller, not discovered`() throws {
        var workspace = Self.workspace
        workspace.derivedDataPath = "/tmp/derived"
        let invocation = try workspace.invocation(jobs: 3, arguments: [])

        #expect(invocation.contains("-derivedDataPath"))
        #expect(invocation.contains("/tmp/derived"))
    }

    @Test
    func `the native slice only, so the workspace path measures what swift build measures`() throws {
        // `swift build` compiles the native slice. `xcodebuild` compiles every
        // architecture in the destination unless told otherwise, which would
        // make the two paths disagree about a package that only fails in a
        // slice one of them never builds.
        #expect(try Self.workspace.invocation(jobs: 3, arguments: []).contains("ONLY_ACTIVE_ARCH=YES"))
    }

    @Test
    func `list enumerates without compiling`() throws {
        var workspace = Self.workspace
        workspace.operation = .list
        let invocation = try workspace.invocation(jobs: 3, arguments: [])

        #expect(invocation.last == "list")
    }

    @Test(arguments: [
        "-workspace",
        "-project",
        "-scheme",
        "-derivedDataPath",
        "-destination",
        "-scheme=Other",
    ])
    func `forwarded arguments cannot override coordinator state`(argument: Swift.String) {
        #expect(
            throws: Build.Error.configuration(
                "xcodebuild argument \(argument) is owned by the build coordinator"
            )
        ) {
            _ = try Self.workspace.invocation(jobs: 3, arguments: [argument])
        }
    }

    @Test
    func `a subject that is not a workspace bundle is refused`() {
        var workspace = Self.workspace
        workspace.bundle = "/checkout/Application"

        #expect(
            throws: Build.Error.configuration("not an Xcode workspace bundle: /checkout/Application")
        ) {
            _ = try workspace.invocation(jobs: 3, arguments: [])
        }
    }

    @Test
    func `a schemeless invocation is refused rather than defaulted`() {
        // `xcodebuild` without `-scheme` picks one itself. On a workspace of
        // hundreds of autogenerated package schemes, whichever it picks builds
        // a fraction of the selection and still exits zero.
        var workspace = Self.workspace
        workspace.scheme = ""

        #expect(
            throws: Build.Error.configuration("an xcodebuild operation requires a scheme")
        ) {
            _ = try workspace.invocation(jobs: 3, arguments: [])
        }
    }
}

extension `Build Institute Tests` {
    @Test(arguments: [
        "/checkout/institute.xcworkspace",
        "/checkout/institute.xcworkspace/",
        "/checkout/institute.xcworkspace///",
    ])
    func `a rendered directory path is accepted with or without a trailing separator`(
        bundle: Swift.String
    ) throws {
        // Whether a rendered `File.Directory` carries a trailing separator is
        // the filesystem layer's business; a guard that depended on the answer
        // would reject a correct bundle at runtime and never in a test.
        var workspace = Build.Workspace(bundle: bundle, scheme: "Institute")
        workspace.operation = .build

        #expect(try workspace.invocation(jobs: 3, arguments: []).contains(bundle))
    }
}
